function n = file_transfer(from,to)
fromd = pwd;
if ~isstruct(from)
    if ~exist(from,'dir')
        error('Source must be either struct array (generated by dir) or directory!');
    end
    fromd = from;
    from = dir(from);
    from = from(3:end);
end
if ~exist(to,'dir')
    if ~mkdir(to)
        error('Destination cannot be created!');
    end
end
h = waitbar(0,['Files waiting for to be transfered: ' num2str(numel(from))]);
for i = 1:numel(from)
    movefile(fullfile(fromd,from(i).name),to);
    waitbar(i/numel(from),h,['Files waiting for to be transfered: ' num2str(numel(from)-i)]);
end
close(h);
n = i;