function n = file_transfer(from,to)
global params
fromd = pwd;
if ~isstruct(from)
    if ~exist(from,'dir')
        error('Source must be either struct array (generated by dir) or directory!');
    end
    if exist(fullfile(from,sprintf('%s.%s.%s',datestr(date,'yyyymmdd'),params.data.LastName,params.data.ID)),'dir')
        from = fullfile(from,sprintf('%s.%s.%s',datestr(date,'yyyymmdd'),params.data.LastName,params.data.ID));
    end
    fromd = from;
    from = dir(from);
    from = from(3:end);
end
if ~exist(to,'dir')
    if ~mkdir(to)
        error('Destination cannot be created!');
    end
end
toMove = true;
h = waitbar(0,['Files waiting for to be transfered: ' num2str(numel(from))]);
for i = 1:numel(from)
    if toMove
        try movefile(fullfile(fromd,from(i).name),to); 
        catch
            toMove = false;
            copyfile(fullfile(fromd,from(i).name),to); 
        end
    else
        copyfile(fullfile(fromd,from(i).name),to); 
    end
    waitbar(i/numel(from),h,['Files waiting for to be transfered: ' num2str(numel(from)-i)]);
end
close(h);
if ~toMove, warndlg('Files has not been removed!'); end
n = i;